# Change these first
owner: 123XYZProducts # Your GitHub username
repo: 123Files-Status # Your GitHub repository name

# Add your sites here
sites:
  - name: 123Files
    url: https://123files.xyz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status.123files.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /123Files-Status
  logoUrl: https://123files.xyz/cache/themes/deluxe/logo.png
  name: 123Files
  introTitle: "**123Files** uptime tracker"
  introMessage: You can use this page to check on any outages, server maintaince and downtimes.
  navbar:
    - title: Status
      href: /
